#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         0
bspc config window_gap           15
bspc config border_radius        20
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

~/.config/polybar/launch.sh &
picom --experimental-backend &
dunst ~/.config/dunst/dunstrc
xfce4-power-manager &
#mpd-rpc &
xwinwrap -g 1366x768 -ov -- mpv --loop  --no-osc -wid WID .backgrounds/cozy-r xwinwrap: window type - ~/.backgrounds/cozy-room-sunset-anime-girl-live-wallpaper.mp4 &
xsetroot -cursor_name left_ptr &
